# Generated by Django 3.2.5 on 2022-08-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default=None, max_length=16, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=None, max_length=64, verbose_name='密码'),
        ),
    ]
