# Generated by Django 3.2.5 on 2022-08-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='default.jpg', max_length=128, upload_to='', verbose_name='头像'),
        ),
    ]
