# Generated by Django 3.2.5 on 2022-08-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='introduction',
            field=models.TextField(default='他什么都没有写哦。', verbose_name='简介'),
        ),
    ]
